%add parameters for the model and runtime settings (all parameters are temporary; current parameters balloon to a huge number)
conf = Config();
params = CytokineParameter();

%if there is real world data to import, import it
if conf.realdata
    %select the data file using the standard windows file viewer
    [filename, pathname] = uigetfile('*.csv', 'Select dataset');
    full_path = fullfile(pathname, filename);
    
    %load data into matlab 
    data_set = readtable(full_path);
end

%swap the values inserted into the params variable to a vector
p0 = params.toVector();
y0 = params.y0; %already inserted as a vector

%check to see if user wants to calculate parameter sensitivity and if there is an available GPU
if conf.sensitivity
    if canUseGPU()
        %fix for modern GPUs that aren't supported for MATLABs version of CUDA
        %double check accuracy by comparing against a run with the CPU
        parallel.gpu.enableCUDAForwardCompatibility(true);
        y0 = gpuArray(y0);
        p0 = gpuArray(p0);
        disp('Running Sensitivity (and Solve) on GPU');
    else
        disp('Running Sensitivity (and Solve) on CPU')
    end
end

%plot each value (using the in-person example)
opts = odeset('RelTol',1e-6,'AbsTol', 1e-9);

figure('Name', 'Full Model +/- drug'); hold on; grid on;
hold on; 
grid on;
xlabel('Time (hours)');
ylabel('Cancer cells C(t)');
title('Cancer-only ODE model: no drug vs drug');

tspan = conf.tspan; %range of hours

%create a ODE object that houses the equations for the mode
f = ode(ODEFcn=@cytokinemodel, InitialValue=y0, Parameters=p0, Sensitivity=odeSensitivity());

for D_value = [0,1]
    %update the drug parameter for no drug vs drug
    current_p = f.Parameters; 
    current_p(10) = D_value;
    f.Parameters = current_p;

    %solve ODE and get a return matrix with the time (t) and the values at t
    sol = solve(f, tspan(1), tspan(2));

    %take time and the cancer cells value from the solution
    t = sol.Time;
    cancer_cells = sol.Solution(2, :);

    %use the same in-person example code of plotting cancer cells with and without the dimensionless drug level
    %the plot does work as intendent but it currently doesn't plot FAST because of huge values generated by the parameters
    if D_value == 0
        plot(t, cancer_cells, 'LineWidth', 2, 'DisplayName', 'No drug (D=0)');
        drawnow;
    else
        plot(t, cancer_cells, 'LineWidth', 2, 'DisplayName', 'Drug (D=1)');
        drawnow;
    end

    if conf.sensitivity
        parametersensitivity(sol)
    end
end
legend('show');

