%select the data file using the standard windows file viewer
%[filename, pathname] = uigetfile('*.csv', 'Select dataset');
%full_path = fullfile(pathname, filename);

%load data into matlab 
%data_set = readtable(full_path);

%add parameters for the model (all are temporary and for testing; current parameters balloon to a huge number)
params = CytokineParameter("rC",0.01,"dC",0.08,"kIC",0.001,"dY",0.2);
y0 = [1e5; 1e2; 0.1];

%swap the values inserted into the params variable to a vector
p0 = params.toVector();

%plot each value (using the in-person example)
opts = odeset('RelTol',1e-6,'AbsTol', 1e-9);

figure('Name', 'Full Model +/- drug'); hold on; grid on;
hold on; 
grid on;
xlabel('Time (hours)');
ylabel('Cancer cells C(t)');
title('Cancer-only ODE model: no drug vs drug');

tspan = [0, 72]; %range of hours

%create a ODE object that houses the equations for the mode
f = ode(ODEFcn=@cytokinemodel, InitialValue=y0, Parameters=p0, Sensitivity=odeSensitivity());

for D_value = [0,1]
    %update the drug parameter for no drug vs drug
    current_p = f.Parameters; 
    current_p(10) = D_value;
    f.Parameters = current_p;

    %solve ODE and get a return matrix with the time (t) and the values at t
    sol = solve(f, tspan(1), tspan(2));

    %take time and the cancer cells value from the solution
    t = sol.Time;
    cancer_cells = sol.Solution(2, :);

    %use the same in-person example code of plotting cancer cells with and without the dimensionless drug level
    %the plot does work as intendent but it currently doesn't plot FAST because of huge values generated by the parameters
    if D_value == 0
        plot(t, cancer_cells, 'LineWidth', 2, 'DisplayName', 'No drug (D=0)');
        drawnow;
    else
        plot(t, cancer_cells, 'LineWidth', 2, 'DisplayName', 'Drug (D=1)');
        drawnow;
    end
end
legend('show');

